apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  annotations:
    kubetide.io/schedule: "0 2 * * *"    # Restart at 2:00 AM daily
    kubetide.io/timezone: "UTC"          # Using UTC timezone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80