{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubetide.fullname" . }}
  labels:
    {{- include "kubetide.labels" . | nindent 4 }}
rules:
  # Allow KubeTide to get, list and watch Deployments, StatefulSets, and DaemonSets
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch", "patch", "update"]
  
  # Allow access to the leader election and health check resources
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  
  # Allow creating events for leader election and other operations
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubetide.fullname" . }}
  labels:
    {{- include "kubetide.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubetide.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubetide.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}